os: Visual Studio 2017

platform: x64

branches:
  # whitelist
  only:
#    - master
    - develop
    - module

install:
  - bash -l -c "pacman -S mingw-w64-x86_64-gtk3"
  - cmd: dir C:\windows\system
