# See also
#   https://www.gtk.org/download/windows.php
#   https://blogs.gnome.org/nacho/2014/08/01/how-to-build-your-gtk-application-on-windows/

os: Visual Studio 2019
version: 0.18.2.2
image:
  - Visual Studio 2019

platform: x64

branches:
  # whitelist
  only:
    - module
#    - master
#    - develop

environment:
  raku_test_all: 1

install:
  - set PATH=C:\msys64\usr\bin;C:\msys64\usr\lib;%PATH%
  - bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gtk3"
#  - bash -lc "pacman -S --noconfirm mingw-w64-x86_64-toolchain base-devel"
  - cmd: dir C:\msys64

  - choco feature enable -n allowEmptyChecksums
  - choco install rakudostar

  - cd %APPVEYOR_BUILD_FOLDER%
  - zef --/test --deps-only install .
#  - prove -l -v -e 'raku' t

build: off

test_script:
  - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\share\perl6\site\bin;%PATH%
  - zef install .
#  - prove -v -e "raku -Ilib" t/

  - cd %APPVEYOR_BUILD_FOLDER%\..

# fetch repository as zip archive
shallow_clone: true

# set clone depth
#clone_depth: 4
